version: '2'
services:
  postgres:
    image: postgres:12.6
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    ports:
      - '6432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgresdata:/var/lib/postgresql/data
    command: postgres -c listen_addresses='*'

  zookeeper:
    image: zookeeper:3.6
    restart: unless-stopped
    hostname: zookeeper
    ports:
      - "3181:2181"
    healthcheck:
      test: [ "CMD", "sh", "-c", "nc -nz 127.0.0.1 2181" ]
      interval: 5s
      timeout: 60s
      retries: 10
    environment:
      ZOO_MY_ID: 1
    volumes:
      - zkdata:/data
      - zkdatalog:/datalog

  minio:
    image: quay.io/minio/minio:RELEASE.2023-03-20T20-16-18Z
    command: server --console-address ":9001" /data
    ports:
      - 9900:9000
      - 9901:9001
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://minio:9000/minio/health/live"
        ]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    hostname: minio
    volumes:
      - miniodata:/data

  druid:
    build:
      context: docker
      dockerfile: druid.Dockerfile
    ports:
      - "9888:8888"
      - "9082:8082"
    healthcheck:
      test: [ "CMD", "curl", "-f", "localhost:8082/status/health" ]
      interval: 5s
      timeout: 5s
      retries: 3
    volumes:
      - .data/druid_data:/opt/druid/var/
    depends_on:
      - zookeeper
      - postgres
      - minio
    environment:
      AWS_REGION: us-east-1

volumes:
  miniodata:
  postgresdata:
  zkdata:
  zkdatalog:
