version: '2'
services:
  postgres:
    image: postgres:12.6
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    ports:
      - '6432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgresdata:/var/lib/postgresql/data
    command: postgres -c listen_addresses='*'

  zookeeper:
    image: zookeeper:3.6
    restart: unless-stopped
    hostname: zookeeper
    ports:
      - "3181:2181"
    healthcheck:
      test: [ "CMD", "sh", "-c", "nc -nz 127.0.0.1 2181" ]
      interval: 5s
      timeout: 60s
      retries: 10
    environment:
      ZOO_MY_ID: 1
    volumes:
      - zkdata:/data
      - zkdatalog:/datalog

  druid:
    build:
      context: docker
      dockerfile: druid.Dockerfile
    ports:
      - "9888:8888"
      - "9082:8082"
    healthcheck:
      test: [ "CMD", "curl", "-f", "localhost:8082/status/health" ]
      interval: 5s
      timeout: 5s
      retries: 3
    volumes:
      - .data/druid_data:/opt/druid/var/
    depends_on:
      - zookeeper
      - postgres
    environment:
      AWS_REGION: us-east-1

volumes:
  postgresdata:
  zkdata:
  zkdatalog:
